site_name: WISO Beschaffung Vertrieb Leistungsabschluss

nav:
  - Übersicht: index.md
  - Wochenüberblick & Einführung: content/einleitung.md

  - Grundlagen:
      - Kundenarten: content/m1/kundenarten.md
      - Vertragsarten:
          - Vertragsarten in der IT – Verantwortung, Ergebnis und Erwartung: content/m1/vertragsarten.md
          - Vertragsabschluss: content/m1/vertragsabschluss.md
          - Vertragsstörungen & Anfechtung: content/m1/vertragsstoerungen_anfechtung.md
      - Gesprächsphasen: content/m1/gespraechsphasen.md

  - Bedarf & Anforderungen:
      - Bedarf und Anforderung: content/m2/bedarf-und-anforderung.md
      - Gruppenarbeit: content/m2/bedarf-und-anforderung-gruppenarbeit.md
      - Reflexion & IPERKA-Transfer: content/m2/iperka_reflexion.md

  - Kalkulation & Wirtschaftlichkeit:
      - Kalkulation in IT-Projekten – Grundlagen, Stundensätze und Rendite: content/m3/kalkulation_grundlagen.md
      - Handelskalkulation – Vom Einkauf bis zum Verkaufspreis: content/m3/kalkulation_handelskalkulation.md
      - Stundensatzkalkulation in IT-Dienstleistungen: content/m3/kalkulation_stundensatz.md
      - Wirtschaftlichkeit von IT-Investitionen – TCO & ROI: content/m3/tco_roi.md

  - Angebotsvergleiche:
      - Angebotsvergleiche bei Beschaffungsmaßnahmen durchführen: content/m4/angebotsvergleich.md
      - Quantitativer Angebotsvergleich – Bezugspreisrechnungen: content/m4/quantitativer_angebotsvergleich.md
      - Qualitative Angebotsvergleiche – Nutzwertanalyse: content/m4/nutzwertanalyse.md

#  - Lieferung, Abnahme & Kontrolle:
#      - Lieferung, Abnahme & Kontrolle: content/m5/lieferung_und_uebergabe.md
#      - Arbeitssicherheit, IT-Schutz & Umweltschutz: content/m5/arbeitssicherheit_und_umweltschutz.md
theme:
  name: material
  palette:
    primary: amber
    accent: indigo
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true

extra_css:
  - stylesheets/logo.css
  - stylesheets/grid.css
  - stylesheets/video_admonition.css
  - stylesheets/python_tutor_admonition.css
  - stylesheets/mermaid.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - macros

extra:
  social:
    - icon: fontawesome/solid/k
      link: https://www.kununu.com/de/qualidy
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/company/qualidy
    - icon: material/google
      link: https://www.google.com/search?sca_esv=7e6ba2047fcb60f3&uds=AMwkrPtyB8MsmozA4Lwzqy2G2HCu-abqzc6moOG48q3gP5dtjTRzC2Ws0eSwcyLXDfZNuYCrZ7ByIreHLG9th3vKLekPoVeey0tumAbet4cVLQRLzdRFhUbOGbnyp3xo1V0hzzaNmkCN&si=AKbGX_rcuucMgom2rba1cdwsvM2SVoIkP2btyqGMV4t0GuHIs4sGV_1tpuqR0YHG4Rzd9SdJcL-lW6E-2aJA5azZLTKkIOrZ2j2aWwoBkVbdEJ0o0GPcQhs%3D&q=Qualidy+GmbH+Rezensionen&sa=X&ved=2ahUKEwibsbnSgcmFAxXNQvEDHaVYCiAQ3PALegQIRxAF
    - icon: fontawesome/solid/globe
      link: https://qualidy.de

watch:
  - tasks

copyright: Copyright &copy; 2025 Qualidy GmbH
